import type { PostedJob } from "@/lib/posted-jobs";

/** Shown when no jobs are posted locally so the Find Work page still demos the UI. */
export const DEMO_OPENINGS: PostedJob[] = [
  {
    id: "demo-driver",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    title: "Driver (LMV / HMV)",
    trade: "Driver",
    location: "Delhi",
    siteAddress: "",
    workersNeeded: 6,
    wageType: "per_month",
    wageAmount: "22000",
    startDate: "",
    duration: "",
    description: "Commercial fleet operations. Valid LMV/HMV licence required.",
    requirements: "",
    postedByEmail: "hr@swiftmove.demo",
  },
  {
    id: "demo-plumber",
    createdAt: new Date(Date.now() - 43200000).toISOString(),
    title: "Plumber (Residential)",
    trade: "Plumber",
    location: "Noida, UP",
    siteAddress: "",
    workersNeeded: 3,
    wageType: "per_day",
    wageAmount: "850",
    startDate: "",
    duration: "30 days",
    description: "High-rise plumbing install. Tools provided on site.",
    requirements: "",
    postedByEmail: "projects@buildwell.demo",
  },
  {
    id: "demo-electrician",
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    title: "Electrician (ITI)",
    trade: "Electrician",
    location: "Gurugram, HR",
    siteAddress: "",
    workersNeeded: 4,
    wageType: "per_month",
    wageAmount: "18000",
    startDate: "",
    duration: "",
    description: "Wiring and panel work. ITI certification preferred.",
    requirements: "",
    postedByEmail: "electro@spark.demo",
  },
];
